name: buildcheck-search
channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- python=3.8
- scipy
- scikit-learn
- matplotlib
- tqdm
- pytorch
- pandas
- transformers
- torchvision
- torchaudio
- tensorboardx
- tensorboard
- pillow
- pip
- pip:
    - torch-summary
    - torchnet
    - rank_bm25
